services:
    minio:
        image: minio/minio
        container_name: nottube-minio
        environment:
            MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
            MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
        ports:
            - "9000:9000"
            - "9001:9001"
        volumes:
            - minio_data:/data
        command: server /data
        restart: always
    postgres:
        image: postgres:16
        container_name: nottube-postgres
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: ${POSTGRES_USERNAME}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB_NAME}
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    minio_data:
    postgres_data:
